# Generated by Django 5.1.1 on 2024-09-24 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can View History")],
            },
        ),
    ]
